export const INTEGRATION_CREDENTIAL_NAME_MAX_LENGTH = 120;
export const INTEGRATION_SECRET_MAX_LENGTH = 4096;
export const INTEGRATION_CHANNEL_MAX_LENGTH = 200;
export const INTEGRATION_TEXT_MAX_LENGTH = 12000;
export const INTEGRATION_REQUEST_TIMEOUT_MS_MIN = 1000;
export const INTEGRATION_REQUEST_TIMEOUT_MS_MAX = 30000;
export const INTEGRATION_REQUEST_MAX_BYTES_MIN = 1024;
export const INTEGRATION_REQUEST_MAX_BYTES_MAX = 65536;
export const INTEGRATION_RESPONSE_MAX_BYTES_MIN = 1024;
export const INTEGRATION_RESPONSE_MAX_BYTES_MAX = 262144;

export const INTEGRATION_ACTION_STATUSES = ["PENDING", "IN_FLIGHT", "SUCCEEDED", "FAILED", "AMBIGUOUS", "CANCELLED"] as const;

export function containsControlCharacters(value: string): boolean {
  return /[\u0000-\u001F\u007F]/u.test(value);
}
